doctrine:
    dbal:
        driver:         pdo_mysql
        host:           '%env(DB_HOST)%'
        port:           '%env(int:DB_PORT)%'
        dbname:         '%env(DB_DATABASE)%'
        user:           '%env(DB_USERNAME)%'
        password:       '%env(DB_PASSWORD)%'
        charset:        utf8mb4
        server_version: '8.0'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            driver:   pdo_sqlite
            dbname:   ':memory:'
            charset:  UTF8